nginx:
  restart: always
  image: nginx:1.9.9
  links:
    - backend:backend
  volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./front/:/usr/share/nginx/html/:ro
  ports:
   - 32769:80

backend:
  restart: always
  image: front_nginx_go:0.1.0
